language: node_js
node_js:
  - '9'
cache:
  directories:
    - node_modules

branches:
  only:
    - master

install:
  - npm install -g yarn
  - yarn install

script:
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/follothru-frontend
  on:
    branch: master
